name = "my-journal-worker"
main = "index.js"
compatibility_date = "2024-03-20"

# Remove the [site] section since we're serving HTML inline now

# This section links your KV Namespace to the worker
[[kv_namespaces]]
binding = "JOURNAL_KV"
id = "6964a75e1e7c4c548babade1b8cfc723"
# You need to get the preview_id from your Cloudflare dashboard for local development
preview_id = "YOUR_PREVIEW_ID_HERE"

# Environment variables section - you need to set JWT_SECRET
[vars]
# Add your JWT secret here or set it via the dashboard
# JWT_SECRET = "your-secret-key-here"

# Observability logs
[observability.logs]
enabled = true
